test_format = 1.0

[default]

    # ------------
    # Tests to run
    # ------------

    exclude = ["install.private"]

    # -------------------------------
    # Default args to use for install
    # -------------------------------
    
        args.weight = "10"
        args.data = "no"
        args.metadata = "no"

test_upgrade_from.053809f.name = "Upgrade from 2.2.0~ynh1"
